"""Tests for reading a cookies.txt and describing it on the settings page."""

from __future__ import annotations

from datetime import datetime, timedelta
from pathlib import Path

from src.cookie_file import CookieFileStatus, describe_cookie_file
from src.log_timezone import LOG_TIME_ZONE
from src.web import routes

NOW = datetime.now(LOG_TIME_ZONE)
# The settings page reads this from config.ini; the tests pin it so the
# wording under test does not move with the deployment.
WARNING_DAYS = 14


def write_cookie_file(
    cookie_file: Path, cookies: list[tuple[str, datetime | None]]
) -> None:
    """Write a Netscape cookie file holding the named cookies.

    Parameters
    ----------
    cookie_file:
        Path to write.
    cookies:
        ``(name, expiry)`` pairs. A ``None`` expiry writes a session cookie,
        which the format stores as a zero.
    """
    lines = ["# Netscape HTTP Cookie File"]
    for name, expiry in cookies:
        expiry_seconds = 0 if expiry is None else int(expiry.timestamp())
        lines.append(f".youtube.com\tTRUE\t/\tTRUE\t{expiry_seconds}\t{name}\tvalue")
    cookie_file.write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_a_missing_file_reports_as_absent(tmp_path: Path) -> None:
    """The settings page must render before any cookie file exists."""
    assert describe_cookie_file(tmp_path / "cookies.txt") == CookieFileStatus()
    assert describe_cookie_file(None) == CookieFileStatus()


def test_the_earliest_sign_in_cookie_sets_the_expiry(tmp_path: Path) -> None:
    """The file stops proving who you are when its first sign-in cookie goes."""
    cookie_file = tmp_path / "cookies.txt"
    first_to_go = NOW + timedelta(days=30)
    write_cookie_file(
        cookie_file,
        [
            ("SID", NOW + timedelta(days=400)),
            ("__Secure-1PSID", first_to_go),
            ("HSID", NOW + timedelta(days=90)),
        ],
    )

    status = describe_cookie_file(cookie_file)

    assert status.exists is True
    assert status.cookie_count == 3
    assert status.login_cookie_count == 3
    assert status.earliest_login_expiry is not None
    assert abs((status.earliest_login_expiry - first_to_go).total_seconds()) < 1


def test_cookies_that_are_not_sign_in_cookies_do_not_set_the_expiry(
    tmp_path: Path,
) -> None:
    """A preference cookie expiring tomorrow says nothing about the sign-in."""
    cookie_file = tmp_path / "cookies.txt"
    write_cookie_file(
        cookie_file,
        [
            ("PREF", NOW + timedelta(days=1)),
            ("SID", NOW + timedelta(days=200)),
        ],
    )

    status = describe_cookie_file(cookie_file)

    assert status.cookie_count == 2
    assert status.login_cookie_count == 1
    assert status.earliest_login_expiry is not None
    assert status.earliest_login_expiry > NOW + timedelta(days=100)


def test_a_session_sign_in_cookie_has_no_date_to_report(tmp_path: Path) -> None:
    """A zero expiry is a session cookie, not a cookie expiring in 1970."""
    cookie_file = tmp_path / "cookies.txt"
    write_cookie_file(cookie_file, [("SID", None)])

    status = describe_cookie_file(cookie_file)

    assert status.login_cookie_count == 1
    assert status.earliest_login_expiry is None


def test_comments_and_damaged_lines_are_skipped(tmp_path: Path) -> None:
    """Real exports carry comments, and a hand-edited file may be broken."""
    cookie_file = tmp_path / "cookies.txt"
    expiry = int((NOW + timedelta(days=50)).timestamp())
    cookie_file.write_text(
        "\n".join(
            [
                "# Netscape HTTP Cookie File",
                "# This file was generated by yt-dlp",
                "",
                "not a cookie line at all",
                ".youtube.com\tTRUE\t/\tTRUE\tnot-a-number\tSID\tvalue",
                f"#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t{expiry}\tHSID\tvalue",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    status = describe_cookie_file(cookie_file)

    # Only the HttpOnly line survives: it is a real cookie behind a prefix,
    # while the others are comments, prose, or an unparsable timestamp.
    assert status.cookie_count == 1
    assert status.login_cookie_count == 1
    assert status.earliest_login_expiry is not None


def test_settings_wording_warns_only_when_expiry_is_close(tmp_path: Path) -> None:
    """Far-off expiry states the date; a near one asks for a new export."""
    cookie_file = tmp_path / "cookies.txt"

    write_cookie_file(cookie_file, [("SID", NOW + timedelta(days=90))])
    far_sentence, far_tone = routes._cookie_expiry_line(
        describe_cookie_file(cookie_file), WARNING_DAYS
    )
    assert far_tone == ""
    assert "Sign-in stops working by" in far_sentence

    write_cookie_file(cookie_file, [("SID", NOW + timedelta(days=3))])
    soon_sentence, soon_tone = routes._cookie_expiry_line(
        describe_cookie_file(cookie_file), WARNING_DAYS
    )
    assert soon_tone == "warn"
    assert "Export a new file soon." in soon_sentence


def test_settings_wording_calls_out_an_expired_or_useless_file(tmp_path: Path) -> None:
    """The two states that break downloads read as problems, not as facts."""
    cookie_file = tmp_path / "cookies.txt"

    write_cookie_file(cookie_file, [("SID", NOW - timedelta(days=2))])
    expired_sentence, expired_tone = routes._cookie_expiry_line(
        describe_cookie_file(cookie_file), WARNING_DAYS
    )
    assert expired_tone == "err"
    assert "Sign-in expired on" in expired_sentence

    write_cookie_file(cookie_file, [("PREF", NOW + timedelta(days=200))])
    missing_sentence, missing_tone = routes._cookie_expiry_line(
        describe_cookie_file(cookie_file), WARNING_DAYS
    )
    assert missing_tone == "warn"
    assert "no YouTube sign-in cookies" in missing_sentence


def test_settings_summary_names_the_file_and_its_size(tmp_path: Path) -> None:
    """The summary answers "which file is in use, and how old is it?"."""
    cookie_file = tmp_path / "cookies.txt"
    write_cookie_file(
        cookie_file,
        [("SID", NOW + timedelta(days=90)), ("PREF", NOW + timedelta(days=90))],
    )

    summary = routes._cookie_summary_line(
        describe_cookie_file(cookie_file), cookie_file
    )

    assert summary.startswith("cookies.txt - 2 cookies - uploaded ")

    missing = tmp_path / "not-there.txt"
    assert routes._cookie_summary_line(describe_cookie_file(missing), missing) == (
        routes.NO_COOKIE_FILE_LABEL
    )
